import {
  PieChart,
  Pie,
  Cell,
  Legend,
} from "recharts";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import { useEffect, useState } from "react";
import axios from "axios";
import MainLayout from "../layouts/MainLayout";

function AnalysisHistory() {

  const [analyses, setAnalyses] =
    useState([]);

  useEffect(() => {
    fetchHistory();
  }, []);

  const fetchHistory = async () => {
    try {

      const res = await axios.get(
        "https://trafficmind-ai.onrender.com/api/analysis"
      );

      setAnalyses(
        res.data.analyses
      );

    } catch (error) {
      console.log(error);
    }
  };

  const chartData = analyses.map(
  (item, index) => ({
    analysis: index + 1,
    vehicles: item.vehicleCount || 0,
  })
);
const congestionData = [
  {
    name: "HIGH",
    value: analyses.filter(
      (a) => a.congestion === "HIGH"
    ).length,
  },
  {
    name: "MEDIUM",
    value: analyses.filter(
      (a) => a.congestion === "MEDIUM"
    ).length,
  },
  {
    name: "LOW",
    value: analyses.filter(
      (a) => a.congestion === "LOW"
    ).length,
  },
];

const COLORS = [
  "#ef4444",
  "#f59e0b",
  "#22c55e",
];

  return (
    <MainLayout>

      <div className="hero-header">

  <div>

    <h1>
      📊 Analysis History Center
    </h1>

    <p
      style={{
        color: "#94a3b8",
        fontSize: "18px",
        fontWeight: "600",
      }}
    >
      Historical AI Analytics
    </p>

    <p
      style={{
        color: "#cbd5e1",
      }}
    >
      Review previous AI traffic
      analyses, congestion trends,
      and recommendation history.
    </p>

  </div>

  <div
    style={{
      background: "#8b5cf6",
      padding: "10px 18px",
      borderRadius: "25px",
      fontWeight: "bold",
    }}
  >
    📊 Analytics Active
  </div>

</div>

    <div className="cards">
  <div className="card">
    <h3>
      📊 Total Analyses
    </h3>

    <h2>
      {analyses.length}
    </h2>
  </div>

  <div className="card">
    <h3>
      🔴 High Congestion
    </h3>

    <h1>
      {
        analyses.filter(
          (a) =>
            a.congestion ===
            "HIGH"
        ).length
      }
    </h1>
  </div>

  <div className="card">
    <h3>
      🟡 Medium Congestion
    </h3>

    <h1>
      {
        analyses.filter(
          (a) =>
            a.congestion ===
            "MEDIUM"
        ).length
      }
    </h1>
  </div>

  <div className="card">
    <h3>
      🟢 Low Congestion
    </h3>

    <h1>
      {
        analyses.filter(
          (a) =>
            a.congestion ===
            "LOW"
        ).length
      }
    </h1>
  </div>

  <div className="card">

  <h3>
    🤖 AI Status
  </h3>

  <h2
    style={{
      color: "#22c55e",
    }}
  >
    ACTIVE
  </h2>

</div>
</div>

<div
className="section-card"
  style={{
    padding: "20px",
    marginBottom: "30px",
  }}
>
  <h2>
    📈 Vehicle Trend
  </h2>

  <ResponsiveContainer
    width="100%"
    height={300}
  >
    <LineChart data={chartData}>
      <CartesianGrid strokeDasharray="3 3" />
      <XAxis dataKey="analysis" />
      <YAxis />
      <Tooltip />
      <Line
  type="monotone"
  dataKey="vehicles"
  strokeWidth={3}
/>
    </LineChart>
  </ResponsiveContainer>
</div>

<div
  className="card"
  style={{
    padding: "20px",
    marginBottom: "30px",
  }}
>
  <h2>
    🚦 Congestion Distribution
  </h2>

  <ResponsiveContainer
    width="100%"
    height={300}
  >
    <PieChart>
      <Pie
        data={congestionData}
        dataKey="value"
        nameKey="name"
        outerRadius={100}
        label
      >
        {congestionData.map(
          (entry, index) => (
            <Cell
              key={index}
              fill={COLORS[index]}
            />
          )
        )}
      </Pie>

      <Tooltip />
      <Legend />
    </PieChart>
  </ResponsiveContainer>
</div>

<div
  className="section-card"
  style={{
    marginBottom: "20px",
  }}
>
  <h2>
    📜 Analysis Records
  </h2>

  <p>
    Historical traffic analysis
    generated by the AI engine.
  </p>
</div>

      {analyses.map((item) => (

        <div
          key={item._id}
          className="card"
          style={{
            marginBottom: "20px",
            padding: "20px",
          }}
        >
         <h3>
  🚗 Vehicles: {item.vehicleCount}
</h3>
         <h3>
  🚦 Congestion: {item.congestion}
</h3>

         <h3>
  📢 Recommendation:
  {" "}
  {item.recommendation}
</h3>

          <p>
            🕒 {
              new Date(
                item.createdAt
              ).toLocaleString()
            }
          </p>

        </div>

      ))}

     

    </MainLayout>
  );
}

export default AnalysisHistory;